---
plugins:
  - babel

env:
  browser: true
  es2020: true

parser: '@babel/eslint-parser'

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-param-reassign: 0
  no-console: 0